---

- hosts: all
  become: true
  tasks:


  - name: install apache and php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php package
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: true
    when: ansible_distribution == "Amazon"
