---

- name: Install apache2
  hosts: all
  become: true
  tasks:


  - name: upadate repo index
    apt:
      update_cache=true

  - name: install apache2 package
    apt:
      name: apache2
      state: absent

  - name: add php support
    apt:
      name: libapache2-mod-php
      state: absent
   
