---

- hosts: all
  become: true
  tasks:

  - name: install updates on Amazon
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Amazon"

  - name: install updates on Ubuntu
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php package on Ubuntu
    tags: apache,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php package on Amazon
    tags: https, amazon
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: start https on Amazon
    tags: apache,amazon,https,service
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Amazon"

  - name: change email for admin
    tags: apache,amazon,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf 
      regexp: '^ServerAdmin'
      line: ServerAdmin mohejaz@somewher.com
    when: ansible_distribution == "Amazon"
    register: httpd

  - name: restart httpd for Amazon
    tags: apache,httpd,amazon
    service:
      name: httpd
      state: restarted
    when: httpd.changed
     
  - name: copy default html for site
    tags: apache,httpd,html
    copy:
      src: default.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: all
  become: true
  tasks:

  - name: add ssh key mohsin
    tags: always
    authorized_key:
      user: mohsin
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDkvU14Lh96os8fqev9+JJai341gUWO5alE9m6YkztboyaIANy7HYiyL7VZmhg5xuU51CJtOrXmtUS6nIkJ/O8sw+yfdyr/wiLnuu+K6RVZGduWaSX+ZzFW0A9vkFGytCDZHOLlcorUDlapZf9fcDsU5hMcOOprcw8KfFAxmUyPqG5Bx0LusyMHRhTznyeC2ze87gvJrcBgWIqBa1Vh+35mz5WBgsUtlR5unr/ZhuM9fO9aBXN6h9EU/0c0LxnMIYCrkSMqa9SmiZQH1uXVWpNExhcln1s8wlDQc+zN1CClKm7yEO+gFp8UpV8IeXATcauB1G6D9UIlM/accjN37vbyudVpy7s117pvsee9LC39HuJt4p1YOVktQ8k7k+1RjMZW/C3tsOdT5+U9YW8p28C7xMwV8/VlZWCgkygTGTD0eQNfm7Pxrt/EN+BxGIc13y87+KwWvkdaQGCd95RXYS4BLTD0aGCbM0mZDOTxS+WGkRwXnBb5boGoWPaXA/IMwFk= ubuntu@ip-172-31-10-154"

- hosts: workstation
  become: true
  tasks:

  - name: install unzip
    package: 
      name: unzip

- hosts: db_server
  become: true
  tasks:

  - name: install mariadb on Ubuntu
    tags: mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb on Amazon
    tags: mariadb, amazon
    dnf:
      name: mariadb105-server 
      state: latest
    when: ansible_distribution == "Amazon"

- hosts: file_server
  become: true
  tasks:
    
    - name: Install Samba
      tags: samba
      package:
        name: samba
        state: latest
