 - name: install mariadb server package (Amazon)
   tags: amazon,db,mariadb
   dnf:
     name: mariadb105-server
     state: latest
   when: ansible_distribution == "Amazon"
 
 - name: install mariadb server
   tags: db,mariadb,ubuntu
   apt:
     name: mariadb-server
     state: latest
   when: ansible_distribution == "Ubuntu"
